-- Generated by nwg-displays on 2026-09-08 at 12:26:51. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "2560x1440@165.01",
    position = "0x0",
    scale = 1.0666667,
    vrr = 0
})
hl.monitor({
    output = "DP-2",
    mode = "2560x1440@165.01",
    position = "2400x0",
    scale = 1.0666667,
    vrr = 0
})
hl.monitor({
    output = "eDP-1",
    mode = "2560x1600@240.0",
    position = "4800x35",
    scale = 1.25,
    vrr = 0
})
