# ENABLE MOUSE
set -g mouse on

# SET MAX HISTORY TO 10,000
set-option -g history-limit 10000

# RIPPLE DELETE WINDOWS
set -g renumber-windows on

# PREFIX+TAB = CTRL+TAB
bind Tab last-window

# PREFIX+{\ or /} TO SPLIT
bind-key "/" split-window -h -c "#{pane_current_path}"
bind-key "\\" split-window -v -c "#{pane_current_path}"

# PREFIX+{< or >} TO SWAP PANES
bind -r "," swap-window -d -t -1
bind -r "." swap-window -d -t +1

# START FROM TAB #1
set -g base-index 1
set -g pane-base-index 1

# ALT+NUM = SELECT TAB
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5

# PREFIX IS CTRL+SPACE
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

# ENABLE 256 BIT COLORS
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# STATUSBAR
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=green'

set -g status-left '#{?client_prefix,#[fg=green],#[fg=green]} '
set -g status-left-length 10

set -g status-right-style 'fg=black bg=yellow'
set -g status-right '#[bg=terminal fg=yellow]#(cd #{pane_current_path}; git rev-parse --is-inside-work-tree &>/dev/null && echo "#[bg=terminal fg=yellow]#[bg=yellow fg=black]$(git rev-parse --abbrev-ref HEAD)#[bg=terminal fg=yellow]" || echo "")'

setw -g window-status-current-style 'fg=black bg=green bold'
setw -g window-status-current-format '#[bg=terminal fg=green]#[bg=green fg=black]#I #W #F#[bg=terminal fg=green]#[bg=green fg=black]'

setw -g window-status-style 'fg=green'
setw -g window-status-separator ''
setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '

setw -g window-status-bell-style 'fg=yellow bg=green bold'
